# Generated by Django 4.2 on 2023-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
