# Generated by Django 4.2 on 2023-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistem',
            fields=[
                ('ids', models.IntegerField(db_column='IDs', primary_key=True, serialize=False)),
                ('aktivnost', models.CharField(max_length=25)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sistem',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='status',
        ),
    ]
